### PR TITLE
Added calculator example

### PR DESCRIPTION
**Pull request by sergeyklay**
Refs: https://github.com/tajmone/lemon-grove/issues/1

### CODE REVIEW

**Comment by tajmone** [comment]
Thanks, that's great!

Could you add a README file briefly describing the example and stating a license (or lack of).

I'd like to keep track of paternity of all contributions, by having authors explicitly mentioned, and especially licenses — chances are these files will end up outside the repository history.

Maybe adding a comment block in the source files mentioning author and license is also a good idea.

What do you think?

**Comment by sergeyklay** [comment]
@tajmone Added copyright note and documentation

**Comment by tajmone** [comment]
Thanks, I'm for squashing this into master, but probably I'll move the example description from `lemon.md` to the README file, just because I've stated that it's the "original documentation" ported to markdown — either that, or just clarify that it was adapted by adding extra contents.

I'm more for the separation of the original upstream files and user-contributed, just because there are some variants of Lemon circulating.

But if that's OK with you I'll just merge and postpone that (after all, there are all the links to the upstream).

**Comment by sergeyklay** [comment]
Well, I'm new with the Adoc format and frankly I don't want to learn yet  another format (after Markdown and Org). So, could you please move documentation by myself?  I also think that it is necessary to create a CONTRIBUTING file that describes all the rules: copyright notice, documentation format, file structure, etc, etc.

n.b. Squashed. But you don't need to ask users to squash commits into one. There is built-in feature: 
image

**Comment by tajmone** [comment]
> Well, I'm new with the Adoc format and frankly I don't want to learn yet another format (after Markdown and Org).

You're right, I was just sharing my thought on GitHub formats difference.

>  So, could you please move documentation by myself? I also think that it is necessary to create a CONTRIBUTING file that describes all the rules: copyright notice, documentation format, file structure, etc, etc.

True, but I've published this repository last night (somewhere in the night), but you're right I should. It's just that I think authors should take their merit for their work — too many people reuse without crediting, and even with public domain is polite (although not mandatory) to credit.

> n.b. Squashed. But you don't need to ask users to squash commits into one. There is built-in feature:

I was asking for your consent.

**Comment by sergeyklay** [comment]
Ideally is to create a README.md file inside `examples` directory too keep documentation near to the code examples. What do you think?

**Comment by tajmone** [comment]
> Ideally is to create a README.md file inside examples directory too keep documentation near to the code examples. What do you think?

Already did! And also added a draft guideline for contributing:

- [`CONTRIBUTING.md`](https://github.com/tajmone/lemon-grove/blob/master/CONTRIBUTING.md)

I've added also a note about the complications of public domain.

I really appreciate your contributed example! Examples are important for newbies, and I really hope that the project will eventually manage to grow and gather the various resources that are spread all over the place.

**Pull request merged**
